Repository Icinga/icingaweb2-module-director, pull requests merged in 2019-04, with the labels that each got.

#1825 Import preview should display data correctly with Black/Whitelisting
  library/Director/Web/Table/ImportsourceHookTable.php
Labels: area/UI, bug

#1816 Improve ActivityLog for services and servicesets
  library/Director/Objects/IcingaServiceSet.php
  library/Director/Web/Controller/ObjectController.php
  library/Director/Web/Widget/ActivityLogInfo.php
Labels: area/UI, bug

#1828 Feature/scheduled downtimes 347
  application/controllers/ScheduledDowntimeController.php
  application/controllers/ScheduledDowntimesController.php
  application/controllers/SuggestController.php
  application/forms/IcingaScheduledDowntimeForm.php
  application/forms/IcingaScheduledDowntimeRangeForm.php
  library/Director/Dashboard/AlertsDashboard.php
  library/Director/Dashboard/Dashlet/ScheduledDowntimeApplyDashlet.php
  library/Director/Dashboard/ObjectsDashboard.php
  library/Director/Db.php
  library/Director/Db/IcingaObjectFilterHelper.php
  library/Director/IcingaConfig/IcingaConfig.php
  library/Director/Objects/IcingaObject.php
  library/Director/Objects/IcingaScheduledDowntime.php
  library/Director/Objects/IcingaScheduledDowntimeRange.php
  library/Director/Objects/IcingaScheduledDowntimeRanges.php
  library/Director/Web/ActionBar/TemplateActionBar.php
  library/Director/Web/Controller/ObjectController.php
  library/Director/Web/Controller/ObjectsController.php
  library/Director/Web/Form/DirectorObjectForm.php
  library/Director/Web/Form/QuickForm.php
  library/Director/Web/Table/ApplyRulesTable.php
  library/Director/Web/Table/IcingaScheduledDowntimeRangeTable.php
  library/Director/Web/Table/ObjectsTable.php
  library/Director/Web/Table/TemplatesTable.php
  library/Director/Web/Tabs/ObjectTabs.php
  library/Director/Web/Tabs/ObjectsTabs.php
  library/Director/Web/Widget/ActivityLogInfo.php
  library/vendor/ipl/Html/FormElement/BaseFormElement.php
  schema/mysql-migrations/upgrade_161.sql
  schema/mysql.sql
  schema/pgsql-migrations/upgrade_161.sql
  schema/pgsql.sql
Labels: enhancement

#1830 Adding s
  application/clicommands/HealthCommand.php
Labels: area/documentation

#1832 ScheduledDowntimes: Hosts with Services, optional
  application/forms/IcingaScheduledDowntimeForm.php
  library/Director/Objects/IcingaScheduledDowntime.php
  schema/mysql-migrations/upgrade_162.sql
  schema/mysql.sql
  schema/pgsql-migrations/upgrade_162.sql
  schema/pgsql.sql
Labels: enhancement

#1836 Avoid caching between multiple runs of sync
  library/Director/Db/Cache/PrefetchCache.php
  library/Director/Import/Sync.php
Labels: area/import and sync, bug

#1840 Ensure MySQL data supports timezones
  library/Director/Db/Migrations.php
  schema/mysql-migrations/upgrade_163.sql
  schema/mysql.sql
Labels: bug, ref/IP, ref/NC
