Repository Icinga/icingaweb2-module-director, pull requests merged in 2019-07, with the labels that each got.

#1898 pgsql: Fix unexpected removal of current deployment
  library/Director/Core/CoreApi.php
Labels: bug, ref/IP

#1887 doc: add a note about director-global being reserved for Director
  doc/10-How-it-works.md
Labels: area/documentation

#1882 Fix ambiguous host_id field
  library/Director/Web/Controller/ObjectsController.php
Labels: bug

#1853 add "icingacli director hostgroups" CLI command for listing hostgroups
  application/clicommands/HostgroupsCommand.php
Labels: enhancement

#1875 ExtensibleSet: Migrate also integers to an array
  library/Director/Web/Form/Element/ExtensibleSet.php
Labels: bug

#873 Document the lookup of structured data sources
  application/forms/SyncPropertyForm.php
Labels: enhancement
