Repository Icinga/icingaweb2-module-director, pull requests merged in 2024-11, with the labels that each got.

#2931 Fix typo in SNMP Data Fields example documentation
  doc/16-Fields-example-SNMP.md
Labels: area/documentation, cla/signed

#2916 DirectorDatalist: Match column types to join tables in postgres by explicit type casting
  library/Director/Objects/DirectorDatalist.php
Labels: cla/signed

#2907 IcingaObjectMultiRelations: Set property `modified` to false when loaded from DB
  library/Director/Objects/IcingaObjectMultiRelations.php
Labels: bug, cla/signed

#2905 Fix sync rule preview in case of boolean properties
  library/Director/Db/Branch/BranchedObject.php
Labels: cla/signed

#2903 PropertyModifierGetHostByName: Fix inet_pton unrecognized address error
  library/Director/PropertyModifier/PropertyModifierGetHostByName.php
Labels: cla/signed

#2902 Basket::setObjects: Reset `$chosenObjects` property only if the given objects is empty
  library/Director/DirectorObject/Automation/Basket.php
Labels: cla/signed

#2900 IcingaMultiEditForm: Fix editing custom vars with space in their name
  application/forms/IcingaMultiEditForm.php
Labels: cla/signed

#2898 IcingaCloneObjectForm: Fix cloning of hosts in director branches
  application/forms/IcingaCloneObjectForm.php
Labels: cla/signed

#2543 Add hasBasketSupport for TimePeriods
  application/controllers/TimeperiodController.php
Labels: cla/signed

#2502 fixes #2393 clusterzone check is not a plugincheck
  library/Director/Objects/IcingaCommand.php
Labels: cla/signed

#2879 Phpstan: Separate workflow
  .github/workflows/php.yml
  .github/workflows/phpstan.yml
Labels: enhancement, cla/signed

#2445 Enrich custom variable lists in monitoring and icingadb details
  library/Director/Objects/DirectorDatafield.php
  library/Director/ProvidedHook/Icingadb/CustomVarRenderer.php
  library/Director/ProvidedHook/Monitoring/CustomVarRenderer.php
  register-hooks.php
Labels: enhancement, ref/NC, cla/signed

#2896 Allow cloning of service sets in branches
  application/forms/IcingaCloneObjectForm.php
  library/Director/Web/Controller/ObjectController.php
Labels: cla/signed
