Repository Icinga/icingaweb2-module-director, pull requests merged in 2024-01, with the labels that each got.

#2840 Fix form field suggestions
  .github/workflows/php.yml
  application/forms/IcingaObjectFieldForm.php
  library/Director/Field/FormFieldSuggestion.php
  library/Director/Test/BaseTestCase.php
  library/Director/Test/IcingaObjectTestCase.php
  library/Director/Test/SyncTest.php
  phpstan-baseline.neon
  phpstan.neon
  test/config/config.ini
  test/php/library/Director/Form/IcingaObjectFieldFormTest.php
  test/php/library/Director/IcingaConfig/StateFilterTest.php
  test/php/library/Director/Objects/HostGroupMembershipResolverTest.php
  test/php/library/Director/Objects/IcingaCommandTest.php
  test/php/library/Director/Objects/IcingaHostTest.php
  test/php/library/Director/Objects/IcingaNotificationTest.php
  test/php/library/Director/Objects/IcingaServiceSetTest.php
  test/php/library/Director/Objects/IcingaServiceTest.php
  test/php/library/Director/Objects/IcingaTemplateResolverTest.php
  test/php/library/Director/Objects/IcingaTimePeriodTest.php
  test/php/library/Director/Resolver/TemplateTreeTest.php
Labels: bug, cla/signed

#2859 IcingaObjectGroup: no membership refresh w/o assign
  doc/82-Changelog.md
  library/Director/Objects/IcingaObjectGroup.php
Labels: cla/signed

#2857 Support Content-Security-Policy
  application/controllers/BasketController.php
  application/controllers/ConfigController.php
  application/controllers/DataController.php
  application/controllers/ImportsourceController.php
  application/controllers/SyncruleController.php
  application/forms/AddToBasketForm.php
  application/forms/IcingaHostForm.php
  application/forms/RemoveLinkForm.php
  library/Director/Web/Controller/ActionController.php
  library/Director/Web/Table/IcingaServiceSetServiceTable.php
  library/Director/Web/Table/ReadOnlyFormAvpTable.php
  library/Director/Web/Table/TemplatesTable.php
  library/Director/Web/Widget/ActivityLogInfo.php
  library/Director/Web/Widget/DeploymentInfo.php
  public/css/module.less
Labels: enhancement, cla/signed
